forums section UI
kihan2518B/Univera pull request #16
Opened 2024-11-29 11:34 UTC by pu9052473

create the UI for the forums section

2024-11-29 12:13 UTC, kihan2518B requested changes

2024-11-29 12:13 UTC, kihan2518B commented on src/app/page.tsx
Make different components for each section

2024-12-18 17:07 UTC, kihan2518B approved these changes

2024-12-18 17:16 UTC, red-devil002 approved these changes

2024-12-18 17:18 UTC, merged